### ISSUE TITLE
Build `cargo doc`

### ISSUE THREAD

**Issue by jamesmunns** [jamesmunns/teensy3-rs#8]
This is blocked by https://github.com/rust-lang/cargo/issues/3107

**Comment by SimonSapin** [comment]
I suggest removing `target = "thumbv7em-none-eabi"` in `.cargo/config` and passing `--target thumbv7em-none-eabi` explicitly to xargo in the Makefile.

**Comment by jamesmunns** [comment]
Yup, that worked! Though I haven't readded the makefile yet, though I don't have a good reason why not. Also the docs look pretty bare 😨

**Comment by jamesmunns** [comment]
Also `xargo build --release --target thumbv7em-none-eabi` fails for me, but `TARGET=thumbv7em-none-eabi xargo build --release` works.

**Comment by jamesmunns** [comment]
Built with newest version.
